version: 2.1

orbs:
  python: circleci/python@2.1.1
  codecov: codecov/codecov@4.0.1

executors:
  my-executor:
    docker:
      - image: cimg/python:3.10

jobs:
  run_tests:
    executor: my-executor
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Build project
          command: |
            poetry install --with test
            poetry build
      - run:
          name: Run tests and generate coverage report
          command: |
            poetry run pytest --cov --cov-config=.coveragerc --cov sigmaepsilon.math
      - run:
          name: List working directory contents
          command: ls -al
      - run:
          name: List home directory contents
          command: ls -a ~
      #- codecov/upload
      - store_artifacts:
          name: Store coverage report as artifact
          path: htmlcov

  deploy_to_test_pypi:
    executor: my-executor
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Build project
          command: |
            poetry install
            poetry build
      - run:
          name: Deploy to test-PyPI
          command: |
            poetry config repositories.testpypi https://test.pypi.org/legacy/
            poetry config pypi-token.pypi $TEST_PYPI_TOKEN
            poetry publish -r testpypi
  
  deploy_to_pypi:
    executor: my-executor
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Build project
          command: |
            poetry install
            poetry build
      - run:
          name: Deploy to PyPI
          command: |
            python -m twine upload --skip-existing dist/*

workflows:
  test_and_deploy_to_test_pypi:
    jobs:
      - run_tests

      - deploy_to_test_pypi:
          context:
            - TestPyPI deploy
          requires:
            - run_tests
          filters:
            branches:
              only:
                - test

      - deploy_to_pypi:
          context:
            - PyPI deploy
          requires:
            - run_tests
          filters:
            branches:
              only:
                - main
